### ISSUE TITLE
Social robot

### ISSUE THREAD

**Issue by tessavdheiden** [vita-epfl/CrowdNav#18]
Hi Changan!

Some interesting results I gained with altering the reward for discomfort distance:
`reward = (dmin - self.discomfort_dist) * self.discomfort_penalty_factor * self.time_step * (1 - (self.robot.vx**2 + self.robot.vy**2)**.5)`

Some additional settings:
`discomfort_dist = 1.2`
`[robot]
visible = true`

What this does, it penalizes the robot not only on getting close to humans, but also if it is close and has a high speed (nervous behavior). 

Please let me know how if you want to have the video and/or let me commit this.

**Comment by ChanganVR** [comment]
I remembered there was some problem in setting visible to be true. Basically the pedestrians will always give their way to the robot since they are running a fixed collision avoidance policy and the objective does not consider cooperation. It would be harder to compare different policies in this case without taking the cooperation into account. What is your opinion on this?

But tuning the discomfort reward function does lead to a better navigational policy (at least showed in the video).
