### ISSUE TITLE
Redundant code in test.py

### ISSUE THREAD

**Issue by tessavdheiden** [vita-epfl/CrowdNav#24]
Hi Chengan,

Please check out this line:
https://github.com/vita-epfl/CrowdNav/blob/64f4f412245ddb4de138de5708075d97d02b5034/crowd_nav/test.py#L78

I don't think you will need it (checking if it is robot.visible). 

Best,
Tessa

**Comment by ChanganVR** [comment]
Hi Tessa,

This is actually not redundant. The invisible case breaks the reciprocal assumption and that's why I added safety space to make up for that. The value of the safety space in the invisible case is supposed to be non-zero, and users can tune this value. Somehow I set it to zero, but I will add one comment to make it clear. 

Thanks,
Changan
